Repository BEIS-Digital-Services/htg-learning-platform, pull requests merged in 2022-08, with the labels that each got.

#165 LP-2939 (htglpacc-86): Alt/aria titles to match actual titles.
  .gitignore
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsSocialMedia/Default.cshtml
  Beis.LearningPlatform.Web/wwwroot/scss/components/_all.scss
  Beis.LearningPlatform.Web/wwwroot/scss/components/social-media/_social-media.scss
  Beis.LearningPlatform.Web/wwwroot/scss/main.scss
Labels: Accessibility, Tested

#178 LP-3277: Fixed empty <label> on feedback form
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_PartialFeedbackPromptJS.cshtml
Labels: Accessibility, Tested

#174 LP-3259: EOI Sign up button now a <button>
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsExpressionOfInterest/Default.cshtml
  Beis.LearningPlatform.Web/wwwroot/js/expression-of-interest.js
  Beis.LearningPlatform.Web/wwwroot/js/site.js
  Beis.LearningPlatform.Web/wwwroot/scss/expression-of-interest.component.scss
Labels: Accessibility, Tested

#180 LP-3283: Fixed duplicate IDs on module landing page
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsLandingPageHero/Default.cshtml
  Beis.LearningPlatform.Web/wwwroot/scss/landingPageHero.scss
  Beis.LearningPlatform.Web/wwwroot/scss/main.scss
Labels: Accessibility, Tested

#181 LP-3284: Set empty alt attribute for link arrow icons
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_PartialSingleLink.cshtml
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsLandingPageHero/Default.cshtml
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsThreeColumnHeroes/Default.cshtml
Labels: Accessibility, Tested

#187 LP-3281: Fix component UI to use header if present
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsNextPageRadioButton/Default.cshtml
Labels: Accessibility, Tested

#185 LP-2929: fix for regression testing- label missing
  Beis.LearningPlatform.Web/Views/Shared/DiagnosticToolFormViews/_PartialRenderDTParentElement.cshtml
  Beis.LearningPlatform.Web/Views/Shared/DiagnosticToolFormViews/_PartialRenderDiagnosticToolEmailAnswer.cshtml
Labels: Accessibility, Tested

#182 LP-3285: Removed unhelpful aria labels
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_Partial2Columns.cshtml
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_PartialHeaderImageColumns.cshtml
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_PartialHeroBannerContent.cshtml
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_PartialStatistics.cshtml
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_PartialTextLinks.cshtml
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsLandingPageHero/Default.cshtml
  Beis.LearningPlatform.Web/Views/Shared/Components/FullSearchArticle/Default.cshtml
Labels: Accessibility, Tested

#184 LP-3279: Remove unused ids on hidden fields
  Beis.LearningPlatform.Web/Views/Shared/DiagnosticToolFormViews/_PartialRenderDTChildElement.cshtml
  Beis.LearningPlatform.Web/Views/Shared/DiagnosticToolFormViews/_PartialRenderDiagnosticTool.cshtml
Labels: Accessibility, Tested

#172 LP-3266 users are unable to leave feedback
  Beis.LearningPlatform.Web/Views/Shared/SatisfactionSurveyViews/_PartialSatisfactionSurveyForm.cshtml
Labels: Tested

#190 LP-3298: Consolidated UAT accessibility issues
  Beis.LearningPlatform.Web/Views/Shared/CMSPageViews/_PartialHeaderImageColumns.cshtml
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsImageItem/Default.cshtml
Labels: Accessibility

#192 remove duplicate ids from EOI inputs
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsExpressionOfInterest/Default.cshtml
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsLinkListHero/Default.cshtml
Labels: Accessibility, Tested

#195 LP-3334: Default cms images to empty alt attribute if title not set
  Beis.LearningPlatform.Web.Tests/ViewComponentTests/CmsImageViewComponentTests.cs
  Beis.LearningPlatform.Web/Models/CmsImageViewModel.cs
Labels: Accessibility, Tested

#191 Lp 1725 code coverage cookie settings
  Beis.LearningPlatform.Web.Tests/ControllerHelperTests/CookiesHelperTests.cs
  Beis.LearningPlatform.Web.Tests/ControllerTests/CookieControllerTests.cs
  Beis.LearningPlatform.Web.Tests/ServicesTests/CookieServiceTests.cs
Labels: Tested

#193 LP-3299: CT product filters fix url hash parsing only expected values
  Beis.LearningPlatform.Web/Views/Shared/ComparisonToolViews/_PartialProduct.cshtml
  Beis.LearningPlatform.Web/wwwroot/js/comparisontool.js
Labels: Tested

#199 LP-3339: Validation errors showing on page load
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsExpressionOfInterest/Default.cshtml
  Beis.LearningPlatform.Web/wwwroot/js/expression-of-interest.js
Labels: Tested

#167 LP-3095 configurable product categories
  Beis.LearningPlatform.Web.Tests/ControllerTests/ComparisonToolControllerTests.cs
  Beis.LearningPlatform.Web/CMSClasses/CMSComparisonToolSearchTag.cs
  Beis.LearningPlatform.Web/ControllerHelpers/ComparisonToolControllerHelper.cs
  Beis.LearningPlatform.Web/Interfaces/ICMSService.cs
  Beis.LearningPlatform.Web/Models/ComparisonToolPageViewModel.cs
  Beis.LearningPlatform.Web/Services/CMSService.cs
  Beis.LearningPlatform.Web/Views/Shared/ComparisonToolViews/_PartialProduct.cshtml
  Beis.LearningPlatform.Web/Views/Shared/ComparisonToolViews/_PartialProductNoJs.cshtml
Labels: Tested

#194 Feature/lp 2956 cms back link component
  Beis.LearningPlatform.Web.Tests/ViewComponentTests/CmsBackLinkViewComponentTests.cs
  Beis.LearningPlatform.Web/Models/CmsBackLinkViewModel.cs
  Beis.LearningPlatform.Web/Views/Shared/Components/CmsBackLink/Default.cshtml
  Beis.LearningPlatform.Web/wwwroot/js/site.js
  Beis.LearningPlatform.Web/wwwroot/scss/main.scss
Labels: Tested

#205 htgci-548 incorrect error message
  Beis.LearningPlatform.Web/Views/Shared/DiagnosticToolFormViews/_PartialRenderDiagnosticTool.cshtml
Labels: Tested

#207 HTGCI-556: Save user email, sessionid, privacy policy optins
  Beis.LearningPlatform.Data/Entities/Skills/SkilledDataResponse.cs
  Beis.LearningPlatform.Data/Entities/Skills/SkillsOneResponse.cs
  Beis.LearningPlatform.Data/Entities/Skills/SkillsThreeResponse.cs
  Beis.LearningPlatform.Data/Entities/Skills/SkillsTwoResponse.cs
  Beis.LearningPlatform.Data/Scripts/R29/HTGCI-556-skilled-data-privacy-accepted.sql
  Beis.LearningPlatform.Library/SkillsOneResponseDto.cs
  Beis.LearningPlatform.Web/ControllerHelpers/DiagnosticToolControllerHelper.cs
Labels: Tested

#210 HTGCI-545/539 Updates email templates to link to skilled module 3
  Beis.LearningPlatform.BL/Configuration/EmailPersonalisationNames.cs
  Beis.LearningPlatform.BL/Services/EmailService.cs
Labels: Tested

#212 HTGCI-551: Update skilled controllers redirecting into CMS pages
  Beis.LearningPlatform.Web.Tests/ControllerTests/SkillsThreeControllerTests.cs
  Beis.LearningPlatform.Web.Tests/diagnosticForm.json
  Beis.LearningPlatform.Web/Controllers/SkillsOneController.cs
  Beis.LearningPlatform.Web/Controllers/SkillsTwoController.cs
  Beis.LearningPlatform.Web/diagnosticForm.json
Labels: Tested
